# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty


# Setup
title:           ''
tagline:          'sangam biradar'
description:      ' <a href="http://sangam14.github.io" target="_blank">resume</a>'
url:              http://engineitops.github.io
baseurl:          /

author:
  name:           'sangam biradar'
  url:            https://www.linkedin.com/in/sangambiradar14/

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/sangam14
